main: main.o stack.o item.o functions.o
	gcc main.o stack.o item.o functions.o -lm -o main

main.o: main.c
	gcc -c main.c

stack.o: stack.c
	gcc -c stack.c

item.o: item.c
	gcc -c item.c

functions.o: functions.c
	gcc -c functions.c